完成rails 作業
zoec0110/rails_project pull request #1
Opened 2022-10-25 13:19 UTC by zoec0110

##PR說明
- 清單操作
- 追蹤股操作
- 功能測試

2022-10-26 08:24 UTC, hzchirs requested changes
未登入使用者進到首頁會直接噴錯，流程上應先判斷使用者登入狀態來決定是先到登入頁還是清單頁

2022-10-26 10:25 UTC, zoec0110 commented
- 在list頁面增加登出使用者
- 若使用者未登入，進入list頁面將會導回登入頁面
- 若使用者已登入，將直接進入list頁面

2022-10-26 13:28 UTC, hzchirs requested changes
兩個比較重要的點：
- 用不到的註解、檔案要刪掉，發 PR 前務必要再檢查一次
- 測試跟功能實做都沒有涵蓋到切換使用者，不符合規格需求，發 PR 前作者應該需要對規格再做一次 check

還有一些需要調整的部分寫在 comment，有不瞭解的再跟我說

2022-10-26 13:28 UTC, hzchirs commented on app/controllers/lists_controller.rb
> +    # @lists = List.all
用不到的註解要清掉

2022-10-26 13:28 UTC, hzchirs commented on app/helpers/list_stocks_helper.rb
> +end
用不到的檔案要清掉

2022-10-26 13:28 UTC, hzchirs commented on app/models/list.rb
> +      self.number = list_qty + 1
進來這個 if 表示 count 已經是 0 了, 裏面沒必要再撈一次 count

2022-10-26 13:28 UTC, hzchirs commented on app/controllers/lists_controller.rb
> +    @list.add_order
清單在建立前都一定要有 `number` 的話，建議用 model 的 callback 來處理

reference
https://guides.rubyonrails.org/active_record_callbacks.html

2022-10-26 13:28 UTC, hzchirs commented on app/controllers/sessions_controller.rb
> +end
這個是有打算要實做嗎？

2022-10-26 13:28 UTC, hzchirs commented on app/models/list.rb
> +      list_order = List.order(:number).last
```suggestion
      list_order = List.maximum(:number)
```

2022-10-26 13:28 UTC, hzchirs commented on app/models/list.rb
> +class List < ApplicationRecord
這邊對 list 的操作都沒有考慮到使用者，也就是使用者 B 的 list number 可能會跟使用者 A 互相影響，會有問題

2022-10-26 13:28 UTC, hzchirs commented on app/models/list.rb
> +    last_list.first.save
- 這種一起發生的操作建議可以包 transaction
- 如同上面提到，沒有考慮到不同使用者的情境

2022-10-26 13:28 UTC, hzchirs commented on spec/features/list_spec.rb
> +  def fill_in_sign_in_and_submit_with
這命名怪怪的，fill in sign in **form** 嗎？
with 又是 with 什麼？

2022-10-26 13:28 UTC, hzchirs commented on spec/features/list_spec.rb
> +    fill_in_sign_in_and_submit_with
如果都需要登入，應該搬到 before 區塊

2022-10-26 13:28 UTC, hzchirs commented on spec/helpers/sessions_helper_spec.rb
> +end
沒用到的檔案要刪掉

2022-10-28 13:24 UTC, hzchirs requested changes

2022-10-28 13:24 UTC, hzchirs commented on app/controllers/list_stocks_controller.rb
> +      ListStockship.create(list: @list, stock: @stock)
建議使用
```suggestion
      @list.stocks << @stock
```

2022-10-28 13:24 UTC, hzchirs commented on app/controllers/list_stocks_controller.rb
> +    @list_stockships.destroy
1. 設定 instance variable 應該用不到
2. model 設定 `has_many` 之後，會多出很多好用的方法，可以的話盡量不要透過 join model 來操作，比較符合物件導向   e.g. `@list.stocks.destroy(Stock.find(params[:id]))`

2022-10-28 13:24 UTC, hzchirs commented on app/models/list.rb
> +        self.number = list_qty + 1
前面判斷是 zero 了，下面直接給 1 就好

2022-10-28 13:24 UTC, hzchirs commented on app/views/sessions/new.html.erb
> +<p>Find me in app/views/sessions/new.html.erb</p>
這有用到嗎？

2022-10-28 13:24 UTC, hzchirs commented on app/models/list.rb
> +    flash[:alert] = "移動失敗! 錯誤訊息: #{e}"
這個會 work 嗎？

2022-10-31 06:15 UTC, hzchirs requested changes

2022-10-31 06:15 UTC, hzchirs commented on spec/models/list_feature_spec.rb
> +  context 'when visit list page' do
```suggestion
  context 'when visits list page' do
```

2022-10-31 06:15 UTC, hzchirs commented on spec/models/list_feature_spec.rb
> +    it 'check list page' do
```suggestion
    it 'checks list page' do
```

2022-10-31 06:15 UTC, hzchirs commented on spec/models/list_feature_spec.rb
> +    it 'create list' do
```suggestion
    it 'creates list' do
```

2022-10-31 06:15 UTC, hzchirs commented on spec/models/list_feature_spec.rb
> +    it 'edit list name' do
```suggestion
    it 'edits list name' do
```

2022-10-31 06:15 UTC, hzchirs commented on spec/models/list_feature_spec.rb
> +    it 'delete list' do
```suggestion
    it 'deletes list' do
```

2022-10-31 13:07 UTC, hzchirs approved these changes

2022-11-01 02:03 UTC, merged